contact_links:
  - name: ğŸ“ƒ Discord.js Guide
    url: https://discordjs.guide/
    about: The official guide for discord.js
  - name: â” Discord.js Official Server
    url: https://discord.gg/bRCvFy9
    about: Please ask questions here
