apiVersion: v2
name: evobot
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "3.0.0"
maintainers:
  - name: drewburr
    email: drew@drewburr.com
    url: https://github.com/drewburr
